services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    networks:
      - app-network
    expose:
      - "3000" # Exposed to nginx within the Docker network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro  
    depends_on:
      - frontend
      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

platform: linux/amd64 # or linux/arm64 based on your system