version: "3.9"

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_NAME=istemlab
      - DATABASE_USER=istemlab
      - DATABASE_PASSWORD=Istemlab@12345
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    env_file:
      - .env
    command: >
      sh -c "python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static:/app/static
    networks:
      - app-network  

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: istemlab
      POSTGRES_USER: istemlab
      POSTGRES_PASSWORD: Istemlab@12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "istemlab"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
