services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_NAME=istemlab 
      - DATABASE_USER=istemlab
      - DATABASE_PASSWORD=Istemlab@12345
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=istemlab
      - POSTGRES_USER=istemlab
      - POSTGRES_PASSWORD=Istemlab@12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: postgres -c listen_addresses='*'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: