version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=postgres
      - DATABASE_USER=istemlab
      - DATABASE_PASSWORD=Istemlab@12345
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: istemlab
      POSTGRES_PASSWORD: Istemlab@12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: