services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_NAME=istemlab   
      - DATABASE_USER=istemlab
      - DATABASE_PASSWORD=Istemlab@12345
      - DATABASE_HOST=147.79.68.249
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network    # Add this

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: istemlab
      POSTGRES_USER: istemlab
      POSTGRES_PASSWORD: Istemlab@12345
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "istemlab"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network    # Add this

networks:    # Add this section
  app-network:
    driver: bridge

volumes:
  postgres_data: