name: Publish Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: istemlab

jobs:
  publish:
    name: Publish Image to GHCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with GitHub Container Registry
        run: |
          echo "${{ secrets.PAT }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          set -e
          IMAGE_TAG=${{ github.sha }}
          docker build . -t ${{ env.REGISTRY }}/${{ github.repository }}:${IMAGE_TAG}
          docker push ${{ env.REGISTRY }}/${{ github.repository }}:${IMAGE_TAG}

  deploy:
    needs: publish
    name: Deploy Image
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect and Pull Image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.WORK_DIR }} &&
            docker compose pull &&
            docker compose up -d
          "

      - name: Clean up SSH keys
        if: always()
        run: rm -rf ~/.ssh