name: Publish Docker Image

permissions:
  contents: read
  packages: write

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: istemlab  # Just the image name

jobs:
  publish:
    name: Publish Image to GHCR
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Authenticate with GHCR
    - name: Authenticate with GitHub Container Registry
      run: |
        echo "${{ secrets.PAT }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
    
    # Step 3: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build . -t ${{ env.REGISTRY }}/${{ github.repository }}:latest
        docker push ${{ env.REGISTRY }}/${{ github.repository }}:latest
