name: publish
on:
 push:
   branches: [ "main" ]
env:
 REGISTRY: ghcr.io
 IMAGE_NAME: ${{ github.actor }}/istemlab:${{ github.sha }}

jobs:
 publish:
   name: publish image
   runs-on: ubuntu-latest
   timeout-minutes: 30
   steps:
   - uses: actions/checkout@v3
   - name: Login
     run: |
       echo ${{ secrets.PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
   - name: Build and Publish Backend
     run: |
       docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} || exit 1
       docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} || exit 1

 