name: Publish Docker Image
on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: istemlab:latest
jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.PAT }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      - name: Build and Push Docker Image
        run: |
          docker build . -t ${{ env.REGISTRY }}/istem-lab/${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/istem-lab/${{ env.IMAGE_NAME }}
  deploy:
    needs: publish
    name: Deploy Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Add this to get your working directory
      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ./.ssh
          echo "$SSH_KEY" > ./.ssh/id_rsa
          chmod 600 ./.ssh/id_rsa
          ssh-keyscan -t rsa ${{ secrets.SSH_HOST }} >> ./.ssh/known_hosts
          
      - name: Connect and Pull Docker Image
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          WORK_DIR: ${{ secrets.WORK_DIR }}
        run: |
          ssh -i "./.ssh/id_rsa" -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd $WORK_DIR && docker compose pull && docker compose up -d"

      - name: Cleanup
        if: always()
        run: rm -rf ./.ssh