name: Publish Docker Image
on:
  push:
    branches: [ "main" ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: istemlab:latest
jobs:
  publish:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.PAT }}" | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      - name: Build and Push Docker Image
        run: |
          docker build . -t ${{ env.REGISTRY }}/istem-lab/${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/istem-lab/${{ env.IMAGE_NAME }}
  deploy:
    needs: publish
    name: Deploy Image
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          
      - name: Connect and Pull Docker Image
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd ${{ secrets.WORK_DIR }} && \
            docker compose pull && \
            docker compose up -d"